name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

# Pipeline/Workflow Triggers
on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:


jobs:
  pr-verification:
    name: Pull Request Validation
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    steps:
      - name: Pull Request Version Validation
        uses: ikmdev/maven-pull-request-version-validation-action@v1.0.0
        
  general-build-job:
    name: General Build
    uses: ikmdev/maven-jpms-test-build-action/.github/workflows/build.yaml@main

  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:          
      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@v3
        with:
          branch_name: ${{github.ref_name}}
    
